repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    namespace: argocd
    labels:
      app: argocd
    chart: argo/argo-cd
    version: ~5.14.1
  - name: argo-workflows
    namespace: argo
    labels:
      app: argo-workflows
    chart: argo/argo-workflows
    version: ~0.22.1